apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cmgfze0d3-nodejs
  janus-idp.io/tekton: cmgfze0d3-nodejs
  backstage.io/kubernetes-id: cmgfze0d3-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cmgfze0d3-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
